### ISSUE TITLE
file_get_contents disabled on server, included a curl attempt before reporting error.

### ISSUE THREAD

**Issue by Capeflair** [DannyBen/php-quandl#2]
If "allow_url_fopen" is not set on the server in php.ini then file_get_contents always returns null. I've included a new version executeDownload that I used to get around this issue. It uses the more secure curl function.

	private function executeDownload($url) {
		if($this->cache_handler == null) {
			$data = @file_get_contents($url);
			if(!$data) {
				if (function_exists('curl_version')) {
					$curl = curl_init();
					 curl_setopt($curl, CURLOPT_URL, $url);
					 curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
					 $data = curl_exec($curl);
					 curl_close($curl);				 
					if(!$data) $this->error = "Invalid URL";
				} else {
					$this->error = "Invalid URL or check php.ini for allow_url_fopen";
				}
			}
		}
		else {
			$data = $this->attemptGetFromCache($url);
		}
		return $data;
	}

**Comment by DannyBen** [comment]
Thanks.

Fixed it in v0.3.3.

Was more work than anticipated, since curl and `file_get_contents` behave a little differently on 404.
Also had to update the tests to support curl and non curl downloads and to also support curl on machines (like mine) where SSL certificates are missing.

Anyways, the `file_get_contents` action (was in two places, also one in the cache download) is now moved and handled by the [download function](https://github.com/DannyBen/php-quandl/blob/master/Quandl.php#L154)
